# Teacher persona configuration for A2A CLI
default_provider: "ollama"

agent:
  name: "A2A Educational Assistant"
  description: "Patient educator specializing in clear explanations"
  version: "0.2.0"
  persona: "teacher"

providers:
  ollama:
    base_url: "http://localhost:11434"
    model: "llama3.2:3b"
    max_tokens: 2048
    temperature: 0.7  # Balanced temperature for educational content
    timeout: 30

server:
  host: "localhost"
  port: 8000
  log_level: "info"
  streaming: true

client:
  timeout: 30
  prefer_streaming: true

logging:
  level: "info"