# ADIOS2 Scientific Data Analyst configuration for A2A CLI
default_provider: "ollama"

agent:
  name: "ADIOS2 Scientific Data Analyst"
  description: "Expert in ADIOS2 file analysis and scientific computing"
  version: "0.2.0"
  persona: "adios2_scientist"

providers:
  ollama:
    base_url: "http://localhost:11434"
    model: "llama3.2:1b"
    max_tokens: 4096  # Larger context for scientific analysis
    temperature: 0.3  # Lower temperature for precise scientific analysis
    timeout: 180  # Longer timeout for complex analysis

# MCP servers configuration
mcp_servers:
  adios2:
    name: "adios2"
    command: ["uv", "--directory", "adios", "run", "adios-mcp"]
    cwd: "."
    enabled: true

server:
  host: "localhost"
  port: 8000
  log_level: "info"
  streaming: true

client:
  timeout: 180  # Much longer timeout for scientific analysis (3 minutes)
  prefer_streaming: true

logging:
  level: "info"